name: Deploy to Azure

on:
  push:
    branches: [ "main" ] # Hoặc "master" tùy nhánh chính của bạn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Bước 1: Cài Java để build code
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Bước 2: Build code ra file .jar
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Bước 3: Đăng nhập vào Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Bước 4: Đóng gói Docker và đẩy lên kho
    - name: Build and push container image
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/mybackend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mybackend:${{ github.sha }}

    # Bước 5: Đẩy vào Web App để chạy
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'agricultural-crop-management-backend' # <--- SỬA TÊN WEB APP BẠN TẠO Ở GIAI ĐOẠN 1 VÀO ĐÂY
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/mybackend:${{ github.sha }}'
